### ISSUE TITLE
Setting `Lattice_SizeY=1` results in infinite(?) run time

### ISSUE THREAD

**Issue by petrelharp** [ThimotheeV/GSpace#2]
Naively modifying the default example to do a 20x1 simulation:
```
%%%%%%%% SIMULATION SETTINGS %%%%%%%%%%%%%%%
Data_filename=Example
Run_Number=10

%%%%%%%% OUTPUT FILE FORMAT SETTINGS %%%%%%%
Genepop=true

%%%%%%%% MARKERS SETTINGS %%%%%%%%%%%%%%%%%%
Chromosome_number=5
Mutation_Rate=0.0005
Mutation_Model=SMM
Allelic_Lower_Bound=1
Allelic_Upper_Bound=200
Sequence_Size = 3

%%%%%%%% RECOMBINATION SETTINGS %%%%%%%%%%%%
Recombination_Rate=0.0005

%%%%%%%% DEMOGRAPHIC SETTINGS %%%%%%%%%%%%%%
%% LATTICE
Lattice_SizeX=20
Lattice_SizeY=1
Ind_Per_Pop=30

%% DISPERSAL
Dispersal_Distribution=uniform
Dist_max = 1,1
Total_Emigration_Rate=0.05

%%%%%%%% SAMPLE SETTINGS %%%%%%%%%%%%%%%%%%%
Sample_SizeX=2
Sample_SizeY=1
Min_Sample_CoordinateX=9
Min_Sample_CoordinateY=1
Ind_Per_Pop_Sampled=5
```
results in a simulation that doesn't appear to ever end - perhaps an infinite coalescence time? Perhaps I've missed something in the documentation, apologies if so! (But in any case, this should probably be caught by the parser.)

Entirely removing the arguments having to do with `Y` results in a simulation that finishes quickly as expected.

**Comment by ThimotheeV** [comment]
We apologize for this error, the program was not correctly considering the options 'Lattice_Size_Y=1' and 'Dist_Max=1,1' (and not  'Dist_Max=1,0') and hence could not build a lattice with reflective boundaries in such case.

 It is now corrected in the new version uploaded on GitHub, and our parser now automatically fixes Dist_Max=0 for the lattice dimension's with size 1.

**Comment by petrelharp** [comment]
> 'Lattice_Size_Y=1' and 'Dist_Max=1,1' (and not 'Dist_Max=1,0') 

Ah-ha! I figured I was putting in silly input there somewhere. Thanks!!
